# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.PositiveIntegerField(unique=True, verbose_name='Postal Code')),
                ('area', models.CharField(max_length=32, verbose_name='Area')),
                ('region', models.CharField(max_length=32, verbose_name='Region')),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=32, verbose_name='Street')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashup.PostalCode', verbose_name='Postal Code Id')),
            ],
        ),
    ]
