# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='area',
            field=models.CharField(max_length=64, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='region',
            field=models.CharField(max_length=64, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='street',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Street'),
        ),
    ]
