# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashup', '0002_auto_20170502_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='postal_code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Postal Code'),
        ),
    ]
