export const GET_POSTAL_CODES = 'GET_POSTAL_CODES';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_SAME = 'GET_ARTICLES_SAME';
export const SEARCH_CODE = 'SEARCH_CODE';
export const SET_CENTER = 'SET_CENTER';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const RESET_PLACE = 'RESET_PLACE';
